### ISSUE TITLE
Build, but errors on running about missing activities

### ISSUE THREAD

**Issue by papyr** [orosandrei/Rehosted-Workflow-Designer#1]
Hi there, great lib :100: however I cannot get it to run, its complaining the dlls cannot be loaded because of system.activities.- _**could not load system.activities or one of its dependencies**_ 
1. I tried to resolve this using nuget but it failed any help would be appreciated, can you please update to include the system.activities dll
2. Also I would be interested in helping out with documentation, as it would help me/others out too. Can you help guide us on what are the steps to follow/create and persist a new activity - for e.g. with a workitems queue, like a document approval system.

thanks
Papi

**Comment by smartmeter** [comment]
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/90e790e4-c0fb-4606-8231-a2e0d57d011e/could-not-load-file-or-assembly-systemactivities-version4000?forum=vseditor

Seems like an issue

**Comment by vladoros** [comment]
Either that or a permissions issue as described [here](https://blogs.msdn.microsoft.com/sayanghosh/2007/04/21/solution-to-could-not-load-file-or-assembly-or-one-of-its-dependencies-access-is-denied/).
Make sure you're running VS under admin.

**Comment by orosandrei** [comment]
@papyr 
1. I think both suggestions from @smartmeter and @vladoros are valid; as a quick resolution, remove the default referenced  system.activities dll and add the one from your system, should work
2. for creating an Approval system, you'll need to implement workflow persistence and create data stores for the state of the workflow + your approval logic - these links should get you in the right direction: 
   [-](url) https://code.msdn.microsoft.com/Windows-Workflow-deed2cd5
   [-](url) https://msdn.microsoft.com/en-us/library/dd489452(v=vs.110).aspx

**Comment by mach37** [comment]
@orosandrei thanks I had the same problem too, I am trying it, but I cannot find the path in windows 10, do I need to install those libs separately.

At my work I cannot get admin rights for win 10, I have another question I will post in separate thread please

**Comment by orosandrei** [comment]
@mach37 
_AddRefference_ to you project and select the correct _System.Activities_ from the results:
![image](https://cloud.githubusercontent.com/assets/6123431/15972623/47fd7b44-2f48-11e6-9156-b5e732331dd3.png)

**Comment by papyr** [comment]
Thanks for that picture :+1: I follow it closely, 

Now I see designer load, but the problem is still there. Then I _deleted_ the _Debug_ folders, and tried to add dll ref again, but same problem is still there _could not load system.activities or one of its_ dependencies.

Should I copy dll locally?
Should I change any permission.

**Comment by sergy79** [comment]
Really good sample better than the other solutions, 
I too am having this issue windows 8.1, anyone find a fix.

**Comment by orosandrei** [comment]
try this:
1. select all references & set "copy local" to "true"
   ![image](https://cloud.githubusercontent.com/assets/6123431/15981610/441adbd8-2f80-11e6-8085-198acb1450a0.png)
2. comment the extra libraries from MainWindow.xaml.cs like below (maybe you don't have them on your system)

![image](https://cloud.githubusercontent.com/assets/6123431/15981618/7116bfbc-2f80-11e6-9b74-7adb347a622f.png)

afterwards rebuild the solution & try running it

**Comment by papyr** [comment]
@orosandrei Step 2 helped me finally!!

Does commenting these lib out impact creating the new workflows or availability of activities, how can I add these back - where should I check to make sure they're available to load, before uncommenting.

Now that its working this is awesome.

When I tried to save the modified XAML in the DB as a string type, I am getting errors. Should I persist as a Blob.

**Comment by papyr** [comment]
Its loading but I have errors on the toolbox items on the left, not sure what causing the numbers, is that correct?

Also is it possible to import other [Workflow Samples like the MSDN windows](https://msdn.microsoft.com/en-us/library/dd483375%28v=vs.110%29.aspx)

![rehostederror](https://cloud.githubusercontent.com/assets/12733414/15987544/27a3bc58-2ff9-11e6-8aa9-da0b6141bc00.png)

**Comment by orosandrei** [comment]
@papyr the activities loaded correctly

**Comment by orosandrei** [comment]
I commented the loading of activity libraries beginning with "Microsoft" namespace, so those will not load by default anymore
