### ISSUE TITLE
Running the workflow from code for ASP MVC

### ISSUE THREAD

**Issue by mach37** [orosandrei/Rehosted-Workflow-Designer#2]
My usage is, only few backend process administrators create wrokflows/process

My request is also similare to @papyr, how can I use my own workflow.... for e.g. process to approve/notify/check if invoice is approved in my ASP MVC 4.5 web app. I am assuming like so... please tell me is this correct or give me some feedback

1. Create/design the process in the hosted designer in the XAML designer
2. Then get an _instance_ from my ASP MVC web app, in a separate dll _as a service_ , 
3. **How can I access the instance and run and check the status here from my ASP MVC web app**, is this the best way, do I need any special rights/admin roles?
4. Is there a way to do both auto transition/trigger (timer) and user approved transition, I could not find the option?

**Comment by orosandrei** [comment]
An approval process implies a long running workflow, so you should consider making use of the WF persistency (create persistency store db); also please note that WF doesn't have an out of the box builtin approval activity or process, so you'll have to implement that according to your business logic (create an activity, use a state machine workflow for implementing the approval BL with States).

For the workflow execution, indeed a workflow service looks like the right choice for handling the workflow executions.

1. Yes, you can offer the user the possibility to change the workflow logic with a rehosted designer. After the changes are done, you'll have to update the XAML in your workflow data store (db), depends on your implementation.
2. The ASP web app should be decoupled from the WF service - you should have a separate service which gets invoked to start the WF execution (via a WF service probably) 
3. You will have to use Bookmarks (see https://blogs.msdn.microsoft.com/bursteg/2009/05/19/wf-4-0-long-running-custom-activities-with-bookmarks-and-nativeactivity/ ); I would make the workflow a State Machine one (https://msdn.microsoft.com/en-us/library/ee264171(v=vs.110).aspx) and waiting for an approval would be one of the states; you would check in that state via the Exit from state section if approval was given or rejected (create a table in you DB to track these approval requests)
4. The State Machine workflow should take care of this for you - https://msdn.microsoft.com/en-us/library/gg983472(v=vs.110).aspx

![image](https://cloud.githubusercontent.com/assets/6123431/15973152/87201b86-2f4a-11e6-8239-67fbfe470e42.png)

**Comment by sergy79** [comment]
Andrei sample is good, but also another sample to access the SVC, take a look at https://github.com/dotnetcurry/Wcf-AngularJS/tree/master/WCF_DataService

Does this designer let you create new processes on the hosted/design surface? When I run it, I do not see an option to drag and drop new components/activity boxes

**Comment by smartmeter** [comment]
I agree this rehosted designer is **very** good :100: andrei's explanation is easier to understand, far better than most, this explanation helped me understand some of the WF pieces also look at his article [here](http://andreioros.com/blog/windows-workflow-foundation-rehosted-designer/). In his above **step 2**, if you copy another sample for the service[ look here ](https://github.com/dotnetcurry/Wcf-AngularJS/tree/master/WCF_DataService) - to access the SVC 

However, saving the Compiled Format is tricky [**Step 1**](http://stackoverflow.com/questions/8930151/how-to-handle-escape-both-single-and-double-quotes-in-an-sql-update-statement/8930229#8930229), 1) because of the quotes, make sure you escape that in SQL and 2) _because_ of option on whether you plan to save the XAML of simply the file location. In any case you can easily save/load XAML and use the XAML in a WPF app but utilizing the XamlReader and XamlWriter classes. http://fritzenhammer.wordpress.com/2006/08/12/xamlwriter-and-xamlreader-wpf-serialization/

```
/// from [channel 9](https://channel9.msdn.com/Forums/TechOff/WPF-Persisting-window-position-size-theme-and-layout-Saving-to-xml-and-application-settings)
using System;
using System.IO;
using HumanIdeas.GUI.Properties;
 
namespace HumanIdeas.GUI
{
       /// <summary>
       /// Interaction logic for Shell.xaml
       /// </summary>
        public partial class Shell {
        private void ResetLayoutButtonClick(object sender, System.Windows.RoutedEventArgs e)
        {
            LoadDefaultLayout();
        }
 
        private void XamRibbonWindowLoaded(object sender, System.Windows.RoutedEventArgs e)
        {
            LoadLayout();
        }
 
        private void XamRibbonWindowClosed(object sender, EventArgs e)
        {
            SaveLayout();
        }        
 
        private void LoadDefaultLayout()
        {
            try
            {
                using (var fs = new FileStream(@"Data\defaultLayout.xml", FileMode.Open, FileAccess.Read))
                {
                    dockingManager.LoadLayout(fs);
                }
 
            }
            catch (FileNotFoundException)
            {
            }
 
        }
 
        private void LoadLayout()
        {
            var curTheme = Settings.Default.CurrentTheme;
            if (curTheme == null | curTheme == String.Empty)  cboThemes.SelectedIndex = 0;
            else cboThemes.SelectedValue = curTheme;
 
                try
                {
                    using (var fs = new FileStream(@"Data\layout.xml", FileMode.Open, FileAccess.Read))
                    {
                        dockingManager.LoadLayout(fs);
                    }
 
                }
                catch (FileNotFoundException)
                {
                    LoadDefaultLayout();
                }
        }
 
        private void SaveLayout()
        {
            Settings.Default.CurrentTheme = cboThemes.SelectedValue.ToString();
            Settings.Default.Save();
 
            using (var fs = new FileStream(@"Data\layout.xml", FileMode.Create, FileAccess.Write))
            {
                dockingManager.SaveLayout(fs);
            }
 
        }
 
    }
}

```

I'm trying to get my hands around this, **can someone tell me what is the [WF manager 1.0 ]**(https://msdn.microsoft.com/en-us/library/jj193528(v=azure.10).aspx) and can we use that with this?
https://msdn.microsoft.com/en-us/library/jj193482(v=azure.10).aspx

**Comment by orosandrei** [comment]
@sergy79 the WF Designer is only available for rehosting in WPF, there is no support for including it in a web app; in the WCF Service you can have a workflow runtime (ex: WorkflowApplication) which you use to execute the workflow triggered from the web app

**Comment by orosandrei** [comment]
@smartmeter Workflow Manager is quite a "heavy" dependency and it adds complexity to both deployment and integration; it does however take care for you of many things, like Workflow versioning. Microsoft uses it in Sharepoint, so it fits enterprise solutions quite well, but I wouldn't add it in small/medium applications.

![image](https://cloud.githubusercontent.com/assets/6123431/15981676/a01fe0e4-2f81-11e6-9a4c-1bd526079fe6.png)

I recommend you take a look at this presentation on the Workflow Manager topic: http://www.slideshare.net/samvanhoutte/workflow-manager-a-technical-overview-sam-vanhoutte

**Comment by mach37** [comment]
@orosandrei @smartmeter I am carefully fowlling the steps to try and create the approval workflow with this rehosted designer.

I am implementing the custom business approval logic on the code-behind, but is it possible to let my users at the UI level also implement/edit custom workflows with the designer.

Please tell me, If I understood @orosandrei in step 1, I have to capture and persist the new XAML Layout, then a webservice can use that layout to figure the next steps based on activities and state machine - is this correct?

How can I add/get more pre-packaged or ready made template for activities and state machines. I think that would be a great idea for this tool as the usage and community grows.

**Comment by orosandrei** [comment]
@mach37  persisting the workflow is for when it is executing, at runtime, when it enters an idle state. 

you can add more activities by creating your own custom activity libraries - see this link https://msdn.microsoft.com/en-us/library/dd489425(v=vs.110).aspx
