### ISSUE TITLE
MSI package

### ISSUE THREAD

**Issue by papyr** [orosandrei/Rehosted-Workflow-Designer#3]
I want to also help bundle this into an [MSI package](http://www.c-sharpcorner.com/UploadFile/1492b1/creating-an-msi-package-for-C-Sharp-windows-application-using-a-v/)

Do I need to use a different template for XAML

**Comment by orosandrei** [comment]
for creating MSI packages I recommend you use WixSharp - https://github.com/Eun/WixSharp
