### ISSUE TITLE
Multiple Workflow Tabs

### ISSUE THREAD

**Issue by vnl** [orosandrei/Rehosted-Workflow-Designer#5]
Is it possible to open more than 1 flow at a time? Like a tabbed feature. May need context perhaps?

**Comment by orosandrei** [comment]
it is possible and quite easy to do; will keep it in mind for a future update

I also answered you in the comments of the blog article: http://andreioros.com/blog/windows-workflow-foundation-rehosted-designer/

**Comment by vnl** [comment]
Thank you. I am experimenting too.
