### ISSUE TITLE
Approval System sample

### ISSUE THREAD

**Issue by mach37** [orosandrei/Rehosted-Workflow-Designer#6]
Hi, is there a sample, 

1) where we can use this to create a workflow.
2) have a something like **document approval** follow this process and then - persist to DB
3) _track the application state for each application in the document approval workflow_.

**Comment by orosandrei** [comment]
1. you can create workflows with the current version
2. document approval can be implemented with workflows, but you'll need to develop your approval business logic with new custom activities
3. the approval applications states can be extracted from the existing workflow trackdata and you can even extend it further with custom tracking logic

I add to the project to-do a card request for an approval activity sample

**Comment by orosandrei** [comment]
Document Approval Process sample https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/samples/document-approval-process

**Comment by mach37** [comment]
Are you not planning on the reshosted designer supporting this
